import { useEffect, useState } from 'react'
import { Activity, CheckCircle2, ListChecks, MapPin, Sparkles, Trash2 } from 'lucide-react'
import CitySearchBox from '../components/CitySearchBox'
import EmptyState from '../components/EmptyState'
import SectionHeader from '../components/SectionHeader'
import ViewAllModal from '../components/ViewAllModal'
import useWeatherApi from '../hooks/useWeatherApi'
import { useApp } from '../context/AppContext'
import { activityTypes } from '../data/demoData'
import { buildActivityAdvice, formatDateTime } from '../utils/helpers'

function PlanCard({ plan, onDelete }) {
  return <article className="plan-card card"><div className="plan-card-head"><span className="mini-icon"><Activity /></span><span><p className="eyebrow">{plan.activity}</p><h3>{plan.city}</h3></span><button className="icon-button danger-icon" onClick={onDelete}><Trash2 size={17} /></button></div><div className="plan-highlight"><Sparkles size={17} /><span><small>Best time</small><strong>{plan.bestTime}</strong></span></div><p>{plan.risks}</p><div className="chip-list">{plan.checklist?.map((item) => <span key={item}>{item}</span>)}</div><small>Saved {formatDateTime(plan.createdAt)}</small></article>
}

export default function ActivityPlanner() {
  const { activeWeather, activeCity, activityPlans, addActivityPlan, deleteActivityPlan, showToast } = useApp(); const { loading, loadWeather } = useWeatherApi()
  const [city, setCity] = useState(activeCity); const [weather, setWeather] = useState(activeWeather); const [form, setForm] = useState({ activity: 'Study', preferredTime: 'Morning' }); const [result, setResult] = useState(null); const [viewAll, setViewAll] = useState(false)
  useEffect(() => { if (activeCity) setCity(activeCity) }, [activeCity])
  const chooseCity = async (nextCity) => { setCity(nextCity); setWeather(await loadWeather(nextCity, activeWeather?.unit || 'celsius')) }
  const generate = () => { if (!city?.name) return showToast({ type: 'error', title: 'Choose a city', message: 'Select a city before generating a suggestion.' }); setResult(buildActivityAdvice(weather, form.activity, form.preferredTime)) }
  const save = () => { if (!result) return showToast({ type: 'guidance', title: 'Generate a plan first', message: 'Create the suggestion before saving it.' }); addActivityPlan({ city: city.name, ...form, ...result }); setResult(null) }
  const deleteMany = (ids) => ids.forEach(deleteActivityPlan)
  return <div className="page private-page content-width-private"><div className="page-heading"><p className="eyebrow">Plan with the forecast</p><h1>Activity Planner</h1><p>Turn current weather into a best time, simple risks, and a practical checklist.</p></div><section className="planner-grid"><div className="card planner-form-card"><SectionHeader eyebrow="Your plan" title="Choose the essentials" /><div className="form-field"><span>City</span><CitySearchBox compact initialValue={city?.name || ''} onSelect={chooseCity} buttonLabel="Find" /></div><label className="form-field"><span>Activity</span><select value={form.activity} onChange={(event) => setForm({ ...form, activity: event.target.value })}>{activityTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="form-field"><span>Preferred time</span><select value={form.preferredTime} onChange={(event) => setForm({ ...form, preferredTime: event.target.value })}><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Flexible</option></select></label><button className="button button-primary" onClick={generate} disabled={loading}><Sparkles size={17} /> Generate Suggestion</button></div><article className="activity-result-card card">{result ? <><span className="result-icon"><CheckCircle2 /></span><p className="eyebrow">Weather-ready suggestion</p><h2>{result.bestTime}</h2><p>{result.summary}</p><div className="result-section"><strong>Weather risks</strong><p>{result.risks}</p></div><div className="result-section"><strong><ListChecks size={17} /> Checklist</strong><div className="checklist">{result.checklist.map((item) => <span key={item}><CheckCircle2 size={15} /> {item}</span>)}</div></div><button className="button button-primary" onClick={save}>Save Plan</button></> : <EmptyState icon={Activity} title="Your suggestion will appear here" message="Choose the activity and generate a plan." />}</article></section><section className="section-block-small"><SectionHeader eyebrow="Saved plans" title="Ideas to revisit" action={activityPlans.length > 2 ? <button className="button button-soft button-small" onClick={() => setViewAll(true)}>View All</button> : null} />{activityPlans.length ? <div className="two-card-grid">{activityPlans.slice(0, 2).map((plan) => <PlanCard key={plan.id} plan={plan} onDelete={() => deleteActivityPlan(plan.id)} />)}</div> : <EmptyState title="No activity plans saved" message="Generate and save a plan to build your personal schedule." />}</section><ViewAllModal open={viewAll} onClose={() => setViewAll(false)} title="All activity plans" items={activityPlans} getSearchText={(item) => `${item.city} ${item.activity} ${item.bestTime}`} onDelete={deleteActivityPlan} onDeleteSelected={deleteMany} renderItem={(plan) => <div className="modal-plan-item"><span className="mini-icon"><MapPin /></span><span><strong>{plan.activity} in {plan.city}</strong><small>{plan.bestTime}</small></span></div>} /></div>
}
